//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Id { get; set; }
        public int RTUId { get; set; }
        public int Value { get; set; }
        public string Type { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual RTU RTU { get; set; }
    }
}
